config/routes.rb
Rails.application.routes.draw do
  resources :wallet_transactions
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :wallet_transactions
  has_one :wallet

  def get_transaction(user)
    user.wallet_transactions.group('strftime("%B-%Y", date)').group('transaction_type').sum(:amount)
  end

  def transaction
    user_hash = {}
    User.all.each do |user|
      user_hash[user.name] = {}
      user_hash[user.name]['Initial Balance'] = user.wallet.total_amount
      monthly_transactions = get_transaction(user)
      monthly_transactions.each do |month, value|
        date = month[0].split('-')
        user_hash[user.name][month[0]] ||= {}
        user_hash[user.name][month[0]][month[1]] = value
      end
    end
    p user_hash
  end
end

app/models/wallet.rb
class Wallet < ApplicationRecord
  has_many :wallet_transactions
  belongs_to :user
end

app/models/wallet_transaction.rb
class WalletTransaction < ApplicationRecord
  belongs_to :user
  belongs_to :wallet

  scope :debit_transaction, -> { where(transaction_type: 'Debit') }
  scope :credit_transaction, -> { where(transaction_type: 'Credit') }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name)
    end
end

app/controllers/wallet_transactions_controller.rb
class WalletTransactionsController < ApplicationController
  before_action :set_wallet_transaction, only: [:show, :edit, :update, :destroy]

  # GET /wallet_transactions
  # GET /wallet_transactions.json
  def index
    @wallet_transactions = WalletTransaction.all
  end

  # GET /wallet_transactions/1
  # GET /wallet_transactions/1.json
  def show
  end

  # GET /wallet_transactions/new
  def new
    @wallet_transaction = WalletTransaction.new
  end

  # GET /wallet_transactions/1/edit
  def edit
  end

  # POST /wallet_transactions
  # POST /wallet_transactions.json
  def create
    @wallet_transaction = WalletTransaction.new(wallet_transaction_params)

    respond_to do |format|
      if @wallet_transaction.save
        format.html { redirect_to @wallet_transaction, notice: 'Wallet transaction was successfully created.' }
        format.json { render :show, status: :created, location: @wallet_transaction }
      else
        format.html { render :new }
        format.json { render json: @wallet_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wallet_transactions/1
  # PATCH/PUT /wallet_transactions/1.json
  def update
    respond_to do |format|
      if @wallet_transaction.update(wallet_transaction_params)
        format.html { redirect_to @wallet_transaction, notice: 'Wallet transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @wallet_transaction }
      else
        format.html { render :edit }
        format.json { render json: @wallet_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wallet_transactions/1
  # DELETE /wallet_transactions/1.json
  def destroy
    @wallet_transaction.destroy
    respond_to do |format|
      format.html { redirect_to wallet_transactions_url, notice: 'Wallet transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wallet_transaction
      @wallet_transaction = WalletTransaction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def wallet_transaction_params
      params.require(:wallet_transaction).permit(:amount, :type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wallet_transactions_helper.rb
module WalletTransactionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CreditBalance</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/wallet_transactions/_form.html.erb
<%= form_with(model: wallet_transaction, local: true) do |form| %>
  <% if wallet_transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wallet_transaction.errors.count, "error") %> prohibited this wallet_transaction from being saved:</h2>

      <ul>
        <% wallet_transaction.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/wallet_transactions/edit.html.erb
<h1>Editing Wallet Transaction</h1>

<%= render 'form', wallet_transaction: @wallet_transaction %>

<%= link_to 'Show', @wallet_transaction %> |
<%= link_to 'Back', wallet_transactions_path %>

app/views/wallet_transactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wallet Transactions</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wallet_transactions.each do |wallet_transaction| %>
      <tr>
        <td><%= wallet_transaction.amount %></td>
        <td><%= wallet_transaction.type %></td>
        <td><%= link_to 'Show', wallet_transaction %></td>
        <td><%= link_to 'Edit', edit_wallet_transaction_path(wallet_transaction) %></td>
        <td><%= link_to 'Destroy', wallet_transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wallet Transaction', new_wallet_transaction_path %>

app/views/wallet_transactions/new.html.erb
<h1>New Wallet Transaction</h1>

<%= render 'form', wallet_transaction: @wallet_transaction %>

<%= link_to 'Back', wallet_transactions_path %>

app/views/wallet_transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @wallet_transaction.amount %>
</p>

<p>
  <strong>Type:</strong>
  <%= @wallet_transaction.type %>
</p>

<%= link_to 'Edit', edit_wallet_transaction_path(@wallet_transaction) %> |
<%= link_to 'Back', wallet_transactions_path %>